name: FastAPI Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update && sudo apt install -y git
            if [ ! -d "~/fastapi-app" ]; then
              git clone git@github.com:your-username/fastapi-app.git ~/fastapi-app
            fi
            cd ~/fastapi-app
            git pull origin main
            docker-compose down
            docker-compose up -d --build
